### ISSUE TITLE
(proposition) Adding binder badge on the repository list

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre.com#16]
We already discussed it with @agahkarakuzu but it could be interresting for some users to have a direct access to the binder badge.
This way they don't need to go though jupyter book.

**Comment by agahkarakuzu** [comment]
I'll add some other elements to that such as DOI, if type publication, link to the original article and a badge if repo has `repo2data` config. These are all added value, but can't see much benefit in adding binder link. Besides, to which notebook would the binder badge in the card point? 

Thinking about a bit more, having binder by-pass kinda defeats the logic of having a jupyter book, where you can interact with outputs objects right away without code execution.

**Comment by emdupre** [comment]
I'm personally +1 on not linking the binder badge. It sort of breaks the conceptual logic of NeuroLibre that we agreed on last time (for example, _not_ hosting software documentation). 

And, practically, I'd second @agahkarakuzu 's point: since we're allowing for single and multi-page notebooks, it'd be hard to know where we'd point the link !

**Comment by ltetrel** [comment]
ok I get your points :+1:
There is still discussion for workshops, where users would mostly interract with binder

**Comment by lunebellec** [comment]
for the workshop we would share the jupyter book link, which features prominently the binder links on top. So I think it is fine under its current form.
