### ISSUE TITLE
header 

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/neurolibre.com#4]
The header currently features a large image. 

I kind of like it, but I would make it smaller.
We also need a very neutral image, that would merge into the white background.
Maybe incorporate the neurolibre in there.

Thoughts @agahkarakuzu ?

**Comment by agahkarakuzu** [comment]
Header: 

![image](https://user-images.githubusercontent.com/9632322/77597922-b364b600-6ed6-11ea-80d2-e38a691e8961.png)

I made it so that the header covers 1/3 of what it was covering before. 

I can design a header image (ideas?), or I can shrink the height even more to make it look like the navbar after scroll, which looks like this: 

![image](https://user-images.githubusercontent.com/9632322/77597892-9f20b900-6ed6-11ea-8436-f31a5ed215f5.png)

I created **svg** drawings of the logo and its outline. 

Favicon
![image](https://user-images.githubusercontent.com/9632322/77597837-76002880-6ed6-11ea-88f5-c0b5c2d1f81a.png)

**Comment by lunebellec** [comment]
I like the simple navbar idea.

The red is very aggressive though. 
I am not sure the Canadian flag makes for a great website color theme. 

Maybe we could go with the white background and red accent like we did in our prototype? http://neurolibre.conp.ca/

**Comment by lunebellec** [comment]
with a screenshot for reference
![navbar_neurolibre_prototype](https://user-images.githubusercontent.com/1670887/77662873-c5843a00-6f52-11ea-8a75-3b96f7d21c3e.png)

**Comment by agahkarakuzu** [comment]
#6
